version: '3.8'
services:
    nginx:
        volumes:
            - '/opt/docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
            - '/opt/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
            - '/opt/docker/nginx/html/:/usr/share/nginx/html'
            #- '/etc/letsencrypt/live/labvsdocker.duckdns.org/fullchain.pem:/etc/letsencrypt/fullchain.pem'  
            #- '/etc/letsencrypt/live/labvsdocker.duckdns.org/privkey.pem:/etc/letsencrypt/privkey.pem'
        ports:
            - '80:80'
            - '443:443'  
        image: nginx
