version: '3.8'
services:
    nginx:
        volumes:
            - '/opt/docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
            - '/opt/docker/nginx/conf.d/default.conf:/etc/nginx/conf-d/default.conf'
            - '/opt/docker/nginx/html/:/usr/share/nginx/html'  
        ports:
            - '80:80'
            - '443:443'  
        image: nginx
